### ISSUE TITLE
(Most Wanted/Carbon) Quit Game button on gamepad doesn't work in menu

### ISSUE THREAD

**Issue by RostovShev03** [xan1242/NFS-XtendedInput#17]
In the latest version I found an issue with quit game button on gamepad. When I press Back/Veiw button on my Xbox gamepad in menu nothing happens at all, but when I press Q key on keyboard it works. Other front-end actions on my gamepad works correctly. I don't know what's the problem.

**Comment by ToruTheRedFox** [comment]
there never was a quit button on console so an action to it is currently not mapped

improvements past console parity will come after every version of the script is stable and rumble is implemented

**Comment by xan1242** [comment]
It is mapped.

Xbox 360: Back
PS3: Select
Xbox One: View
PS4/PS5: Share

In MW and Carbon it only works during FrontEnd mode. In Carbon, in addition to that, it only works on the main menu (due to the way its state manager is coded).

Meaning in MW, you can press it anywhere during FrontEnd/menus.
In Carbon, you can only press it at the main menu.

Now my question is - are you pressing it where it's designed to be pressed or not? It is fully working for me.

**Comment by HarGabt** [comment]
@xan1242 this feature works up until 1.6 version
Starting from 1.7 it stopped working.

**Comment by xan1242** [comment]
Yeah I see the mistake, it happened during UC definition implementation for the compiler directives...

It'll get fixed very soon.

**Comment by xan1242** [comment]
fixed in [429371b](https://github.com/xan1242/NFS-XtendedInput/commit/429371ba736c1ac91e47c38bd1e42ab942af9e96)

Closing.
