### ISSUE TITLE
(Discussion) More button prompt support for various controllers

### ISSUE THREAD

**Issue by TorutheRedFox** [xan1242/NFS-XtendedInput#19]
it's at https://github.com/TorutheRedFox/NFS-XtendedInput
not launching a PR yet as not all icons (based on PS2 but upscaled) are done yet (using PS4 icons as placeholders)

the folder they're in is also a bit of a mess at the moment

**Comment by ToruTheRedFox** [comment]
screenshots using a TPK hacked up using TexEd (because the version of the tool you have up doesn't like the textures and fails for some reason)
the textures, apart from being 4x the resolution, are basically the PS2 icons from the PS2 demo of Carbon
![image](https://user-images.githubusercontent.com/15708278/166258916-7afbf08d-27d8-484d-990f-10dd9460aa52.png)
![image](https://user-images.githubusercontent.com/15708278/166259107-13c70c84-13fc-45ce-8e62-3e73bc100790.png)
![image](https://user-images.githubusercontent.com/15708278/166259140-78ed3166-bc79-47ea-b91c-6ea1a7e68e33.png)
![image](https://user-images.githubusercontent.com/15708278/166259217-bc4d6b75-58a8-42d6-ae5c-9d425acb0e98.png)

**Comment by AeroWidescreen** [comment]
My current plan is to redraw all of the icons from PlayStation 3, Xbox 360, and (maybe) Gamecube in high quality vector. Just waiting on Xan to dump the textures for me. So if you want to port the original icons, then I think that's a cool idea, but there should be no need to upscale them after I'm finished.

**Comment by ToruTheRedFox** [comment]
the upscaling is just to make them higher res than the OG PS2 icons, and since I was going to be redrawing them anyway, I've decided to just go the extra mile and upscale them to the 128x128 the other icons are

**Comment by ToruTheRedFox** [comment]
how are you supposed to get the tpk tool to work right?
I've managed to get it to export a TPK, and the size seems correct, but the textures show up blank ingame

**Comment by TorutheRedFox** [comment]
found an actually working copy of the tool and they look fantastic
![image](https://user-images.githubusercontent.com/15708278/166458868-832c6e79-a464-4546-84fb-f8700556c932.png)
![image](https://user-images.githubusercontent.com/15708278/166459238-6baa0df3-403c-4ac4-b8d9-1af441c3cc99.png)

**Comment by xan1242** [comment]
My TPK tool is sadly a mess right now and I'm planning a total rewrite of it. (I don't know what I was thinking about file paths)

That being said, well, I've sent the textures already to him and I'll implement them in the code (just add the switching groups and hashes and it should be fine).

No need to work on this from your end for now. PS2 and PS3 textures are the same ones anyway so it shouldn't matter in the end. I've ripped them straight from Carbon PS3 and sent them to Aero for turning them into vector images and upscaling.

**Comment by TorutheRedFox** [comment]
started the PR https://github.com/xan1242/NFS-XtendedInput/pull/21

**Comment by TorutheRedFox** [comment]
> I forgot to get rid of that, that was so I can actually run it myself (as I use Windows 7 on my main machine as I'm wary of upgrading as to not break something critical to my server)
I'll keep the define in, albeit commented out with an explanation as to what it's for so you can direct people there incase you get complaints ;P (plus the original condition to use 9.1.0 couldn't be met due to weirdness with Windows headers breaking stuff if _WIN32_WINNT is set to 0x0601 which is why I added it for myself in the first place)

**Comment by TorutheRedFox** [comment]
check https://github.com/TorutheRedFox/NFS-XtendedInput/ if it's satisfactory (the icons still are placeholders btw, so keep that in mind. I can replace them once they're done, or just launch the PR now, and you can merge it once the icons are done and replace the placeholders with the actual ones immediately, or do a manual merge and exclude mine, and you get the idea)

**Comment by TorutheRedFox** [comment]
full opacity buttons in MW 
![image](https://user-images.githubusercontent.com/15708278/166745490-32bda8db-4621-4b9b-953f-75b989c1a93e.png)
![image](https://user-images.githubusercontent.com/15708278/166745602-bdf80031-72a5-4720-81b0-65b314d14fcb.png)

**Comment by xan1242** [comment]
No need to bother yourself with this. I really appreciate your help, but at the moment Aero is the one who I'm working with on this subject.

They do look fine in the shots you provided, but I like Aero's approach better (which is redrawing them in vectors from ripped textures and rendering them again).

**Comment by AeroWidescreen** [comment]
Just so you know, I've finished all of the icons already. Only waiting on Xan to add them now. All textures are based on the PS3 and Xbox 360 version of Carbon.

![MW](https://i.imgur.com/JMapfV7.png)
![CARBON](https://i.imgur.com/lcAOGDd.png)

**Comment by TorutheRedFox** [comment]
also the corners on the X button look a tad bit...
round?

**Comment by TorutheRedFox** [comment]
I'll leave this as a discussion for more controllers to be added

**Comment by TorutheRedFox** [comment]
@AeroWidescreen would you be able to send me the original globaltextures tpks for PS3 and 360? I want to try something

**Comment by AeroWidescreen** [comment]
> also the corners on the X button look a tad bit... round?

The corners on the original texture have pointed ends, due to obvious resolution limitations. When displayed in-game, these corners appear rounded.

![Texture](https://i.imgur.com/5YvIhkM.png)
![PS3_720p](https://i.imgur.com/K2Q1Etc.png)
![PS3_Upscaled](https://i.imgur.com/j62ZX8y.png)

So my interpretation is that they're supposed to be rounded.

> would you be able to send me the original globaltextures tpks for PS3 and 360? I want to try something

I don't have the original tpks, only the textures that Xan gave me. He's offline right now... but I assume he won't mind if I share it.
[Download](https://mega.nz/file/xbwnmSDK#wEUOvpl-sRJQau5o1PwwT5EBP-hR9uDncsDXKIiAqUw)

**Comment by xan1242** [comment]
> I don't have the original tpks, only the textures that Xan gave me. He's offline right now... but I assume he won't mind if I share it.

Of course I won't, just send 'em!

I'm just busy and not home.

**Comment by TorutheRedFox** [comment]
thx

**Comment by TorutheRedFox** [comment]
at 720p the corners look pretty sharp to me
![image](https://user-images.githubusercontent.com/15708278/167272525-f2526b45-ea79-47d1-8ba3-5cd75a90f76d.png)

**Comment by TorutheRedFox** [comment]
ok so they bothered to actually swap button texture names on PS3 but not any other platform

cool

**Comment by AeroWidescreen** [comment]
> at 720p the corners look pretty sharp to me

This is the result of me creating two vector lines, two pixels wide, with rounded corners, and no anti-aliasing applied.

Redrawn:
![Redrawn](https://imgur.com/7dl3id5.png)
Original:
![Texture](https://i.imgur.com/5YvIhkM.png)

As you can see, the "x" I redrew with rounded corners looks exactly the same as the original texture because it's supposed to be rounded. That's as clear-cut as it gets.

You can always use the originals if you prefer them. In fact, I wouldn't mind if Xan added them as another option for purists. But when it comes to the "x" being rounded or not, I think I've provided enough evidence that it's supposed to be that way.

**Comment by TorutheRedFox** [comment]
huh

**Comment by TorutheRedFox** [comment]
actually speaking about other options, button icon sets would be a neat idea (as in maybe have an INI option to change the TPK it loads)

**Comment by xan1242** [comment]
Since GitHub has an actual discussions feature, I'm moving the conversations to its own thread [here].(https://github.com/xan1242/NFS-XtendedInput/discussions/28)

Closing this issue.
