### ISSUE TITLE
Give specific/proper names to HUDACTION DPAD input entries in the ini file

### ISSUE THREAD

**Issue by Nowena** [xan1242/NFS-XtendedInput#40]
Just noticed some entries for HUDACTION DPAD input from in-game controls don't have specific names relating to what they actually do, like ENGAGE_EVENT does (PAD_UP). PAD_LEFT should say 'world map', PAD_RIGHT should say 'SMS system' and PAD_DOWN should say 'blacklist menu' 🥳

**Comment by xan1242** [comment]
The config file is what it is.

A definition to tie buttons to specific actions.

Black Box decided to name these in this fashion, so it wouldn't be very wise to change the naming scheme. The ingame settings menu even says the same things, so the request is, to me, illogical.

That being said, I will implement the in game configuration menu in the future anyways, so that should be user friendly enough.

**Comment by Nowena** [comment]
Oh I didn't know that's what black box did. Just wondered why the engage event entry was labelled and the others weren't.
