### ISSUE TITLE
[PS] Right Stick also controls manual gearing

### ISSUE THREAD

**Issue by kye-l** [xan1242/NFS-XtendedInput#66]
Hi, for some reason the right stick camera controls are also controlling gearing. Is there any way to unbind the camera controls so that I can just use RS for gearing? Let me know, thank you.

**Comment by xan1242** [comment]
Yeah camera control isn't a feature of this mod or the stock game so I can't help you in the context of this project specifically.

If you're playing Pepega Edition (which I am pretty sure you are), then that's a different story. Pepega Edition is NOT Pro Street.

In that case, since I worked on it directly, I can tell you that PepegaScript has the camera controls hardcoded. We hadn't intended for users to reconfigure the camera controls, but what we can do in this instance is add a toggle to enable/disable camera control on the RS in the next version of Pepega Edition.

Also, for Pepega Edition for any further inquiries you have to ask in the Discord server or open a ticket and we can take a look at it there.

**Comment by TorutheRedFox** [comment]
> Yeah camera control isn't a feature of this mod or the stock game so I can't help you in the context of this project specifically.
> 
> If you're playing Pepega Edition (which I am pretty sure you are), then that's a different story. Pepega Edition is NOT Pro Street.
> 
> In that case, since I worked on it directly, I can tell you that PepegaScript has the camera controls hardcoded. We hadn't intended for users to reconfigure the camera controls, but what we can do in this instance is add a toggle to enable/disable camera control on the RS in the next version of Pepega Edition.
> 
> Also, for Pepega Edition for any further inquiries you have to ask in the Discord server or open a ticket and we can take a look at it there.

buttons for shifting are better anyways so remap shifting there instead

**Comment by xan1242** [comment]
I'll leave it up to users for now and think about it later.

If defaults suck, blame Black Box, not me.
